#@baseUrl = http://localhost:7165/api
@baseUrl = https://demo-connected-factory-service-ci.azurewebsites.net/api

### Health Check
Get  {{baseUrl}}/health
content-type: application/json
x-functions-key: <KEY>

### Health Check Readiness
Get  {{baseUrl}}/health/readiness
content-type: application/json
x-functions-key: <KEY>

### Add Measurement
POST  {{baseUrl}}/Measurement
content-type: application/json
x-functions-key: <KEY>

{
  "name": "temperature",
  "value": "32"
}
