trigger:
  branches:
    include:
    - main
pool:
      vmImage: 'ubuntu-latest'

variables:
  rootDirectory: 'Services/Demo.Services.ConnectedFactory'
  azureSubscription: 'Demo Account'
  resourceGroupName: 'demo-connected-factory-service-ci'
  region: 'eastus'

stages:
- stage: Build
  displayName: Build stage
s
  jobs:
  - job: Build
    displayName: Buildd
    steps:

    - task: DotNetCoreCLI@2
      displayName: 'Function - Build project'
      inputs:
        projects: ' $(rootDirectory)/**/*.csproj'
        arguments: '--output publish_output --configuration Release'
    - task: DotNetCoreCLI@2
      displayName: 'Publish project'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '$(rootDirectory)/**/*.csproj'
        arguments: '--configuration Release --output $(build.artifactstagingdirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'App'
        publishLocation: 'pipeline'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: ' Infrastructure'
        artifact: 'Infrastructure'
        publishLocation: 'pipeline'

- template: ado-release-pipeline-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'CI'
    azureSubscription: ${{ variables.azureSubscription }}
    resourceGroupName: 'demo-connected-factory-service-ci'
    storageAccountName: 'democfservicecisa'
    functionAppName: 'demo-connected-factory-service-ci'
    cosmosDbAccountName: 'demo-connected-factory-service-db-ci'
    region: 'eastus'
    packageName: ${{ variables.packageName }}

